import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.io" />
      </Head>
      <main className="font-bodyFont">New Portfolio</main>
    </>
  );
}
